// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs4L2ZzVG6WvIEGE2Bqnsy6SZZdG_n-Ss',
    appId: '1:564287568921:web:4c46c96248d86c77663e88',
    messagingSenderId: '564287568921',
    projectId: 'flutter-social-media-53fdf',
    authDomain: 'flutter-social-media-53fdf.firebaseapp.com',
    storageBucket: 'flutter-social-media-53fdf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJg1wx84djAYJaZKhFD8dE0DzdREXistQ',
    appId: '1:564287568921:android:0c5a48646c85adf1663e88',
    messagingSenderId: '564287568921',
    projectId: 'flutter-social-media-53fdf',
    storageBucket: 'flutter-social-media-53fdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY9WywLA2URgsVpHuXaXK7PchAtQVchkg',
    appId: '1:564287568921:ios:0b9f0594d103721b663e88',
    messagingSenderId: '564287568921',
    projectId: 'flutter-social-media-53fdf',
    storageBucket: 'flutter-social-media-53fdf.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
